name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Use the branch you want to deploy from, such as main or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../  # Use ./ if everything (HTML, CSS, JS) is in the root directory.
